### ISSUE TITLE
why not use native Promise?

### ISSUE THREAD

**Issue by 75lb** [then/fs#5]
Is there any special reason this library doesn't use native promises when available?

**Comment by MiniXC** [comment]
I'd also like to use this with native promises.
It's possible to use a workaround with [proxyquire](https://github.com/thlorenz/proxyquire).

```
const proxyquire = require('proxyquire');
const fs = proxyquire('then-fs', { promise: Promise });
```

But that's not a very nice solution...

**Comment by 75lb** [comment]
never mind, i switched to [fs-then-native](https://github.com/75lb/fs-then-native).
